### ISSUE TITLE
When I try to share the .theme folder from the files app, I don't get blizzardboard as an option.

### ISSUE THREAD

**Issue by EVO428** [BenjaminHornbeck6/BlizzardBoard#2]
![image](https://user-images.githubusercontent.com/115941852/196057975-fb0a6b94-1f81-4c16-9fd5-34ed492b0fd5.jpeg)

**Comment by BenjaminHornbeck6** [comment]
The .theme should be a folder but sometimes the files app turns in into a file. Try the latest stable ipa of my app and see if you can share. Please tell me if you can. https://appinstallerios.com/TrollStoreIPAs/BlizzardBoard.ipa
