### ISSUE TITLE
Cant import .theme folder

### ISSUE THREAD

**Issue by FrxstYiojeoijh** [BenjaminHornbeck6/BlizzardBoard#3]
when i try to share the .theme folder BlizzardBoard doesnt show up.

**Comment by EVO428** [comment]
Check out this video. It helped me: https://www.youtube.com/watch?v=A-7cFfF3MEg

**Comment by BenjaminHornbeck6** [comment]
If it looks like a file that’s your problem (it’s a problem with iOS)
