### ISSUE TITLE
Ios 15.0.2 trollstore

### ISSUE THREAD

**Issue by Airmancooma** [BenjaminHornbeck6/BlizzardBoard#4]
If I put anything in the .theme folder the application does not start and crashes. In the factory file app, I can't share the .theme files with it because it's not there in the apps to share with. It is ios 15.0.2 what could be the reason for this ?(Trollstore)

**Comment by EVO428** [comment]
Check out this video. It helped me: https://www.youtube.com/watch?v=A-7cFfF3MEg

**Comment by Airmancooma** [comment]
> Check out this video. It helped me: https://www.youtube.com/watch?v=A-7cFfF3MEg

I already tried but it didn't work

**Comment by Vegeta4444** [comment]
i have the same Problem
